version: "3.9"

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=30d"
      - "--web.enable-lifecycle"
    expose:
      - 9090
    logging:
      options:
        max-size: "10m"

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      #- GF_SMTP_ENABLED=true
      #- GF_SMTP_HOST=<host:port>
      #- GF_SMTP_USER=<username>
      #- GF_SMTP_PASSWORD=<password>
      #- GF_SMTP_CERT_FILE=<empty>
      #- GF_SMTP_KEY_FILE=<empty>
      #- GF_SMTP_SKIP_VERIFY=<false>
      #- GF_SMTP_FROM_ADDRESS=<from_address>
      #- GF_SMTP_FROM_NAME=<from_name>
      #- GF_SMTP_EHLO_IDENTITY=<instance_name>
      #- GF_SMTP_STARTTLS_POLICY=<empty>
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_EXPLORE_ENABLED=true
      - GF_ALERTING_ENABLED=false
      - GF_UNIFIED_ALERTING_ENABLED=true
      - GF_UNIFIED_ALERTING_SCREENSHOTS_CAPTURE=true
      - GF_SERVER_ROOT_URL=https://${FQDN:-metrics.demo.com}/
      - GF_RENDERING_SERVER_URL=http://grafanarenderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_LOG_FILTERS=rendering:debug
    expose:
      - 3000
    logging:
      options:
        max-size: "10m"

  grafanarenderer:
    image: grafana/grafana-image-renderer:latest
    container_name: grafanarenderer
    restart: unless-stopped
    expose:
      - 8081
    logging:
      options:
        max-size: "10m"

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/ssl/:/etc/ssl/
    ports:
      - "443:443"
    logging:
      options:
        max-size: "10m"
