global:
  scrape_interval:     5s
  evaluation_interval: 5s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'cc_openmetrics'

# A scrape configuration containing exactly one endpoint to scrape.
# Replace JOB_NAME, metrics_path, FQDN, QUEUE_NAME and QUEUE_EXTENSION.
scrape_configs:
  - job_name: 'JOB_NAME'
    metrics_path: /api/service/monitor/cc/QUEUE_UUID/TOKENUSER_TOKENPASS/metrics
    scheme: https
    scrape_interval: 5s
    static_configs:
      - targets: ['FQDN:443']
        labels:
          pbx: 'FQDN'
          queue: 'QUEUE_NAME'
          extqueue: 'QUEUE_EXTENSION'
